version: "3"
services:
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    image: jules.filiot/nestjs-server
    environment:
      DB_TYPE: ${DB_TYPE}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      POSTGRES_SYNC: false
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PORT: ${DATABASE_PORT}
      APP_PORT: ${APP_PORT}
    ports:
      - "3000:3000"
    container_name: jules-filiot-nestjs-server
    volumes:
      - /app/node_modules
      - .:/app
