version: "3"
services:
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    image: jules.filiot/nestjs-server
    environment:
      DB_TYPE: ${{ env.DB_TYPE }}
      POSTGRES_HOST: ${{ env.DATABASE_HOST }}
      POSTGRES_USER: ${{ env.DATABASE_USER }}
      POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ env.DATABASE_NAME }}
      POSTGRES_SYNC: 'false'
      JWT_SECRET: ${{ env.JWT_SECRET }}
      DATABASE_PORT: ${{ env.DATABASE_PORT }}
      APP_PORT: ${{ env.APP_PORT }}
    ports:
      - "3000:3000"
    container_name: jules-filiot-nestjs-server
    volumes:
      - /app/node_modules
      - .:/app
