version: "3"
services:
  db:
    image:  postgres
    restart: always 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
    container_name: postgres-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  nestjs:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: jules.filiot/nestjs-server
    environment: 
      DB_TYPE: ${DB_TYPE}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      POSTGRES_SYNC: false
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PORT: ${DATABASE_PORT}
      APP_PORT: ${APP_PORT}
    ports: 
      - "3000:3000" # expose-to-the-world : only-in-the-docker
    container_name: jules-filiot-nestjs-server
    depends_on: 
      - db
    volumes: 
      - .:/app
      - /app/node_modules