version: "3"
services:
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    image: ghcr.io/julesfiliot/jules-filiot-back
    environment:
      DB_TYPE:
        external: true
      POSTGRES_HOST:
        external: true
      POSTGRES_USER:
        external: true
      POSTGRES_PASSWORD:
        external: true
      DATABASE_NAME:
        external: true
      POSTGRES_SYNC: 'false'
      JWT_SECRET:
        external: true
      DATABASE_PORT:
        external: true
      APP_PORT:
        external: true
    ports:
      - "3000:3000"
    container_name: julesfiliot/container/jules-filiot-back
    volumes:
      - /app/node_modules
      - .:/app
