name: Deploy to GCP

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: jules-filiot-server
  IMAGE_NAME: ghcr.io/julesfiliot/jules-filiot-back
  IMAGE_TAG: ${{ github.sha }}
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_JSON }}
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker-compose build --pull
          docker tag ${{ env.IMAGE_NAME }} gcr.io/${{ env.GCP_PROJECT_ID }}/jules-filiot-back:${{ env.IMAGE_TAG }}
          echo ${{ secrets.GIT_TOKEN }} | docker login ghcr.io -u JulesFiliot --password-stdin
          gcloud auth configure-docker
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/jules-filiot-back:${{ env.IMAGE_TAG }}

      # Deploy the image to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: jules-filiot-nest-server
          region: us-central1
          image: gcr.io/${{ env.GCP_PROJECT_ID }}/jules-filiot-back:${{ env.IMAGE_TAG }}
